-- | 
-- Module       : Tarski.Language.Java.Parametric.Full
-- Copyright    : (C) 2012-2013 Tarski Technologies, All Rights Reserved
-- Author       : James Koppel
-- 
-- A parametric syntax for Java which perfectly follows the original
-- 
-- Most of this file has been autogenerated from the non-parametric syntax in
-- 'Language.Java.Syntax' using the @comptrans@ library.

module Tarski.Language.Java.Parametric.Full
  (
    module Tarski.Language.Java.Parametric.Full.Types
  , module Tarski.Language.Java.Parametric.Full.Trans
  ) where

import Tarski.Language.Java.Parametric.Full.Types
import Tarski.Language.Java.Parametric.Full.Trans